Repository h2floh/GeoDistributedAzureBot, pull requests merged in 2019-12, with the labels that each got.

#9 add aad application creation pwsh script
  README.md
Labels: documentation

#10 AB#332 Updating Readme
  Doc/img/architecture.png
  GeoBot/GeoBot.Tests/README.md
  GeoBot/GeoBot/README.md
  LetsEncrypt/Archive/README.md
  README.md
Labels: documentation

#11 Commenting Terraform Scripts
  Deploy/IaC/bot.tf
  Deploy/IaC/data.tf
  Deploy/IaC/main.tf
  Deploy/IaC/output.tf
  Deploy/IaC/regions.tf
  Deploy/IaC/variables.tf
Labels: documentation

#14 Update to support PowerShell Core & Linux
  Deploy/.gitignore
  Deploy/ActivateSSL.ps1
  Deploy/CheckExistingSSL.ps1
  Deploy/CheckServiceAvailability.ps1
  Deploy/CreateOrImportSSL.ps1
  Deploy/CreateRegionVariableFile.ps1
  Deploy/CreateSSL.ps1
  Deploy/DeactivateSSL.ps1
  Deploy/DeployBot.ps1
  Deploy/DeployInfrastructure.ps1
  Deploy/DeployLUIS.ps1
  Deploy/ExportSSL.ps1
  Deploy/HelperFunctions.ps1
  Deploy/ImportSSL.ps1
  Deploy/OneClickDeploy.ps1
  Deploy/OneClickDestroy.ps1
  Deploy/RetrieveWebChatLink.ps1
  Deploy/ValidateParameter.ps1
  README.md
Labels: documentation, enhancement

#17 Added PowerShell style documentation
  Deploy/ActivateSSL.ps1
  Deploy/CheckExistingSSL.ps1
  Deploy/CreateOrImportSSL.ps1
  Deploy/CreateSSL.ps1
  Deploy/DeactivateSSL.ps1
  Deploy/DeployBot.ps1
  Deploy/DeployInfrastructure.ps1
  Deploy/DeployLUIS.ps1
  Deploy/ExportSSL.ps1
  Deploy/HelperFunctions.ps1
  Deploy/ImportSSL.ps1
  Deploy/OneClickDeploy.ps1
  Deploy/OneClickDestroy.ps1
  Deploy/RetrieveWebChatLink.ps1
  Deploy/ValidateParameter.ps1
  README.md
Labels: bug, documentation
