Repository h2floh/GeoDistributedAzureBot, pull requests merged in 2020-01, with the labels that each got.

#18 change variable type from string to boolean
  Deploy/CreateOrImportSSL.ps1
  Deploy/CreateSSL.ps1
  Deploy/OneClickDeploy.ps1
Labels: bug

#19 Adding Documentation
  Deploy/CreateSSL.ps1
  Deploy/HelperFunctions.ps1
  Doc/CreateMarkdown-FromPS1.md
  Doc/CreateMarkdown-FromPS1.ps1
  Doc/Deploy/ActivateSSL.md
  Doc/Deploy/CheckExistingSSL.md
  Doc/Deploy/CreateOrImportSSL.md
  Doc/Deploy/CreateSSL.md
  Doc/Deploy/DeactivateSSL.md
  Doc/Deploy/DeployBot.md
  Doc/Deploy/DeployInfrastructure.md
  Doc/Deploy/DeployLUIS.md
  Doc/Deploy/ExportSSL.md
  Doc/Deploy/ImportSSL.md
  Doc/Deploy/OneClickDeploy.md
  Doc/Deploy/OneClickDestroy.md
  Doc/Deploy/RetrieveWebChatLink.md
  Doc/Deploy/ValidateParameter.md
  Doc/GeoBot/README.md
  Doc/flowchart/ActivateSSL.flowchart.svg
  Doc/flowchart/CheckExistingSSL.flowchart.svg
  Doc/flowchart/CreateOrImportSSL.flowchart.svg
  Doc/flowchart/CreateSSL.flowchart.svg
  Doc/flowchart/DeactivateSSL.flowchart.svg
  Doc/flowchart/DeployBot.flowchart.svg
  Doc/flowchart/DeployInfrastructure.flowchart.svg
  Doc/flowchart/DeployLUIS.flowchart.svg
  Doc/flowchart/ExportSSL.flowchart.svg
  Doc/flowchart/ImportSSL.flowchart.svg
  Doc/flowchart/OneClickDeploy.flowchart.svg
  Doc/flowchart/OneClickDestroy.flowchart.svg
  Doc/flowchart/RetrieveWebChatLink.flowchart.svg
  Doc/flowchart/ValidateParameter.flowchart.svg
  Doc/flowchart/activatessl.flowchart
  Doc/flowchart/checkexistingssl.flowchart
  Doc/flowchart/createorimportssl.flowchart
  Doc/flowchart/createssl.flowchart
  Doc/flowchart/deactivatessl.flowchart
  Doc/flowchart/deploybot.flowchart
  Doc/flowchart/deployinfrastructure.flowchart
  Doc/flowchart/deployluis.flowchart
  Doc/flowchart/exportssl.flowchart
  Doc/flowchart/importssl.flowchart
  Doc/flowchart/oneclickdeploy.flowchart
  Doc/flowchart/oneclickdestroy.flowchart
  Doc/flowchart/retrievewebchatlink.flowchart
  Doc/flowchart/validateparameter.flowchart
  Doc/img/geobot_cancel.png
  Doc/img/geobot_intentechoresult.png
  Doc/img/geobot_intentechostate.png
  Doc/img/geobot_waitingstate.png
  Doc/sequencechart/botstate.sequencechart
  Doc/sequencechart/botstate.sequencechart.svg
  README.md
  WebChat/index.html
Labels: documentation

#20 Improved documentation
  Deploy/OneClickDeploy.ps1
  Doc/CreateMarkdown-FromPS1.ps1
  Doc/Deploy/CreateOrImportSSL.md
  Doc/Deploy/CreateSSL.md
  Doc/Deploy/DeactivateSSL.md
  Doc/Deploy/OneClickDeploy.md
  Doc/Deploy/OneClickDestroy.md
  Doc/Deploy/RetrieveWebChatLink.md
  Doc/Deploy/ValidateParameter.md
  Doc/flowchart/CreateOrImportSSL.flowchart.svg
  Doc/flowchart/OneClickDeploy.flowchart.svg
  Doc/flowchart/OneClickDestroy.flowchart.svg
  Doc/flowchart/activatessl.flowchart
  Doc/flowchart/checkexistingssl.flowchart
  Doc/flowchart/createorimportssl.flowchart
  Doc/flowchart/createssl.flowchart
  Doc/flowchart/deactivatessl.flowchart
  Doc/flowchart/deploybot.flowchart
  Doc/flowchart/deployinfrastructure.flowchart
  Doc/flowchart/deployluis.flowchart
  Doc/flowchart/exportssl.flowchart
  Doc/flowchart/importssl.flowchart
  Doc/flowchart/oneclickdeploy.flowchart
  Doc/flowchart/oneclickdestroy.flowchart
  Doc/flowchart/retrievewebchatlink.flowchart
  Doc/flowchart/validateparameter.flowchart
  Doc/img/blog_appinsights.png
  Doc/img/blog_appinsights2.png
  Doc/img/blog_botconfiguration.png
  Doc/img/blog_channelregistration.png
  Doc/img/blog_cname.png
  Doc/img/blog_keyvaultaccesspolicies.png
  Doc/img/blog_keyvaultconfig.png
  Doc/img/blog_simulatefailure.png
  Doc/img/blog_simulatefailure_bot1.png
  Doc/img/blog_simulatefailure_bot2.png
  Doc/img/blog_simulatefailure_bot3.png
  Doc/img/blog_trafficmanager.png
  Doc/img/blog_trafficmanagerprofile.png
  Doc/img/blog_webappcert.png
  Doc/img/blog_webappconfig.png
  Doc/img/geobot_intentechoresult.png
Labels: documentation

#24 Fixes #23
  Deploy/IaC/bot.tf
  Deploy/IaC/data.tf
  Deploy/IaC/variables.tf
Labels: bug

#26 Adding Pipelines as Code
  AzureDevOps/Agent/pipelineagent.dockerfile
  AzureDevOps/agentbuild.yaml
  AzureDevOps/geobotbuild.yaml
  AzureDevOps/keyvaultcertbotbuild.yaml
  AzureDevOps/oneclickdeploytest.yaml
  README.md
  SSL/Docker/Dockerfile
Labels: enhancement

#27 Resolve CD issue on PR
  AzureDevOps/agentbuild.yaml
  AzureDevOps/keyvaultcertbotbuild.yaml
Labels: Security

#31 Change build pool, add README
  AzureDevOps/README.md
  AzureDevOps/agentbuild.yaml
  AzureDevOps/geobotbuild.yaml
  AzureDevOps/keyvaultcertbotbuild.yaml
  AzureDevOps/oneclickdeploytest.yaml
Labels: bug, documentation

#32 Update WebChat code to enable speech functionality and change speech controller
  GeoBot/GeoBot/Controllers/SpeechController.cs
  GeoBot/GeoBot/Helpers/Token.cs
  WebChat/index.html
Labels: enhancement

#33 Delete ambiguous helper class as a two separate class for Directline and Speech
  GeoBot/GeoBot/Controllers/DirectlineController.cs
  GeoBot/GeoBot/Controllers/SpeechController.cs
  GeoBot/GeoBot/Helpers/Token.cs
Labels: enhancement

#35 Update README.md
  README.md
Labels: documentation

#36 Adding Terraform Remote State Store
  Deploy/ActivateSSL.ps1
  Deploy/CheckExistingSSL.ps1
  Deploy/CreateSSL.ps1
  Deploy/DeactivateSSL.ps1
  Deploy/DeployBot.ps1
  Deploy/DeployInfrastructure.ps1
  Deploy/DeployLUIS.ps1
  Deploy/ExportSSL.ps1
  Deploy/HelperFunctions.ps1
  Deploy/IaC/bot.tf
  Deploy/IaC/main.tf
  Deploy/IaC/regions.tf
  Deploy/ImportSSL.ps1
  Deploy/InitTerraform.ps1
  Deploy/OneClickDeploy.ps1
  Deploy/OneClickDestroy.ps1
  Deploy/RetrieveWebChatLink.ps1
  Deploy/SSLActivation/main.tf
  Deploy/SSLIssuing/main.tf
  Deploy/ValidateParameter.ps1
  Doc/AzureDevOps/README.md
  Doc/Deploy/ActivateSSL.md
  Doc/Deploy/CreateSSL.md
  Doc/Deploy/DeployInfrastructure.md
  Doc/Deploy/InitTerraform.md
  Doc/Deploy/OneClickDeploy.md
  Doc/Deploy/OneClickDestroy.md
  Doc/flowchart/OneClickDeploy.flowchart.svg
  Doc/flowchart/OneClickDestroy.flowchart.svg
  Doc/flowchart/activatessl.flowchart
  Doc/flowchart/checkexistingssl.flowchart
  Doc/flowchart/createorimportssl.flowchart
  Doc/flowchart/createssl.flowchart
  Doc/flowchart/deactivatessl.flowchart
  Doc/flowchart/deploybot.flowchart
  Doc/flowchart/deployinfrastructure.flowchart
  Doc/flowchart/deployluis.flowchart
  Doc/flowchart/exportssl.flowchart
  Doc/flowchart/importssl.flowchart
  Doc/flowchart/oneclickdeploy.flowchart
  Doc/flowchart/oneclickdestroy.flowchart
  Doc/flowchart/retrievewebchatlink.flowchart
  Doc/flowchart/validateparameter.flowchart
  README.md
Labels: bug, documentation, enhancement

#38 CI/CD Multi Stage Pipeline Examples
  AzureDevOps/CICDExamples/bot.yaml
  AzureDevOps/CICDExamples/destroy.yaml
  AzureDevOps/CICDExamples/iac.yaml
  AzureDevOps/CICDExamples/init.yaml
  AzureDevOps/CICDExamples/luis.yaml
  AzureDevOps/CICDExamples/stages/bot.yaml
  AzureDevOps/CICDExamples/stages/endtoend.yaml
  AzureDevOps/CICDExamples/stages/iac.yaml
  AzureDevOps/CICDExamples/stages/jobs/destroy.yaml
  AzureDevOps/CICDExamples/stages/jobs/steps/bot.yaml
  AzureDevOps/CICDExamples/stages/jobs/steps/iac.yaml
  AzureDevOps/CICDExamples/stages/jobs/steps/logout.yaml
  AzureDevOps/CICDExamples/stages/jobs/steps/luis.yaml
  AzureDevOps/CICDExamples/stages/jobs/steps/prep.yaml
  AzureDevOps/CICDExamples/stages/luis.yaml
Labels: documentation, enhancement
